"""empty message

Revision ID: 0f5a90e48626
Revises: 
Create Date: 2022-11-22 10:00:04.084318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f5a90e48626'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=75), nullable=False),
    sa.Column('work_1_title', sa.String(length=75), nullable=False),
    sa.Column('work_1_artist', sa.String(length=75), nullable=False),
    sa.Column('work_1_image_url', sa.String(length=2048), nullable=False),
    sa.Column('work_1_display_date', sa.String(length=50), nullable=False),
    sa.Column('work_1_marker_obj', sa.JSON(), nullable=True),
    sa.Column('work_2_title', sa.String(length=75), nullable=False),
    sa.Column('work_2_artist', sa.String(length=75), nullable=False),
    sa.Column('work_2_image_url', sa.String(length=2048), nullable=False),
    sa.Column('work_2_display_date', sa.String(length=50), nullable=False),
    sa.Column('work_2_marker_obj', sa.JSON(), nullable=True),
    sa.Column('comparison_text', sa.String(length=3000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=75), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('set_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=75), nullable=False),
    sa.Column('artist', sa.String(length=75), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=False),
    sa.Column('display_date', sa.String(length=50), nullable=False),
    sa.Column('marker_obj', sa.JSON(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('set_cards')
    op.drop_table('sets')
    op.drop_table('comparisons')
    op.drop_table('users')
    # ### end Alembic commands ###
